### ISSUE TITLE
borrow_mut?

### ISSUE THREAD

**Issue by kornelski** [indiv0/lazycell#54]
Is there a safety reason why `LazyCell` does not implement `borrow_mut()`? (assuming it'd be on `&mut self`).

**Comment by indiv0** [comment]
Yes. While technically possible (e.g. `unsafe { (*self.inner.get()).as_mut() }`, it's not implemented because of the same warnings listed [here](https://doc.rust-lang.org/core/cell/struct.UnsafeCell.html) for `UnsafeCell`. The general idea being is it then becomes the user's responsibility to ensure there aren't multiple active mutable references at the same time, etc.

Another (and actually probably the primary) reason why it's not implemented is I've never needed it. Do you have a particular use-case for it or are you just asking in general?

P.S. apologies for not replying earlier, I somehow missed your comment in my GitHub notifications.

**Comment by indiv0** [comment]
I'm going to close this as resolved for now. If you have a concrete use-case for `borrow_mut`, feel free to let me know and I'll open this issue back up.

**Comment by kornelski** [comment]
Sorry for the lack of response earlier. I just hacked my solution with an `unsafe` block without the lazycell and I forgot how I was planning to change it.

**Comment by indiv0** [comment]
Alright :)
