### ISSUE TITLE
LazyCell::borrow_with might be unsound

### ISSUE THREAD

**Issue by indiv0** [indiv0/lazycell#66]
To avoid the kind of shenanigans described by dbaupp [here](https://www.reddit.com/r/rust/comments/5vs9rt/lazycell_a_rust_library_providing_a_lazilyfilled/de527xm/), an `assert!` must be added between the closure call and the `LazyCell` initialization in `borrow_with`.

Additionally, a test needs to be added to ensure that a dangling pointer can't be created in this situation.

**Comment by novacrazy** [comment]
I think it would make more sense to rename `borrow_with` to `borrow_or_fill_with` and add a `'static` bound to the closure. That stops the closure from taking any non-static references, and issues a compile-time error for the code described in the reddit comment.

```rust
pub fn borrow_or_fill_with<F>(&self, init: F) -> &T where F: FnOnce() -> T + 'static {
    let mut slot = unsafe { &mut *self.inner.get() };
    if !slot.is_some() {
        *slot = Some(init());
    }

    slot.as_ref().unwrap()
}
```

then the following code:

```rust
let cell = LazyCell::<Box<i32>>::new();

let mut reference = None::<&i32>;

cell.borrow_or_fill_with(|| {
    cell.fill(Box::new(1));
    reference = cell.borrow().map(|r| &**r);
    Box::new(2)
});
```

will give errors saying `cell` and `reference` don't live long enough, and adding `move` to the closure will disallow calling the `borrow_with`/`borrow_or_fill_with` because it would attempt to move the `cell` instance.

If that is a satisfactory solution I can open up a pull request.

**Comment by novacrazy** [comment]
And yeah, standard library APIs don't usually have that `'static` lifetime bound restriction on similar methods, like `Option`s `unwrap_or_else`, but those consume the `Option` instance, rather than modifying it.

**Comment by indiv0** [comment]
Hmm. That looks good to me, I'm just trying to think of any possible edge cases or unforseen side effects. I'll think about it some more and let you know.

**Comment by novacrazy** [comment]
Well, it would prevent using non-static references to initialize the cell, so if a library user wanted to use a local value it would have to be moved.

Have you looked at the [move_cell RFC](https://github.com/rust-lang/rfcs/blob/master/text/1651-movecell.md) any? That might give a few ideas for things, not just related to this issue.

**Comment by indiv0** [comment]
I haven't had a chance to take a look at the move_cell RFC, but nox and eddyb have also offered comments on the issue in #68.

**Comment by nox** [comment]
The `move_cell` RFC is pretty unrelated to `LazyCell` AFAICT.

**Comment by indiv0** [comment]
Also, I'm personally really busy during this week, so I won't have much time to really take a look at this issue until the end of the week.
